import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import type { PutObjectInput, StorageProvider, StoredObject } from "./types";

const TYPES: Record<string, string> = { ".jpg": "image/jpeg", ".png": "image/png", ".webp": "image/webp" };

/** Development adapter: files under a local directory. Never used on Vercel (read-only, ephemeral disk). */
export class LocalStorageProvider implements StorageProvider {
  private readonly root: string;

  constructor(directory: string) {
    this.root = path.resolve(directory);
  }

  /** Keys are generated by the server, but refuse anything that could leave the storage directory. */
  private resolve(key: string): string {
    const target = path.resolve(this.root, key);
    if (target !== this.root && !target.startsWith(this.root + path.sep)) throw new Error("Invalid storage key");
    return target;
  }

  async put(input: PutObjectInput): Promise<StoredObject> {
    const target = this.resolve(input.key);
    await mkdir(path.dirname(target), { recursive: true });
    await writeFile(target, input.body);
    return { key: input.key, sizeBytes: input.body.byteLength, contentType: input.contentType };
  }

  async get(key: string): Promise<{ body: Uint8Array; contentType: string } | null> {
    try {
      const target = this.resolve(key);
      const body = await readFile(target);
      return { body, contentType: TYPES[path.extname(target).toLowerCase()] ?? "application/octet-stream" };
    } catch {
      return null;
    }
  }

  async delete(key: string): Promise<void> {
    await rm(this.resolve(key), { force: true });
  }
}
