import { and, eq, isNull } from "drizzle-orm";
import type { DbExecutor } from "@/lib/db";
import { exerciseMuscles, exercises } from "@/lib/db/schema";
import { BASE_EXERCISES } from "@/data/starter/base-exercises";
import { EXERCISE_CATALOG } from "@/data/starter/exercise-catalog";
import { EXERCISE_LIBRARY } from "@/data/starter/exercise-library";
import { EXERCISE_MEDIA } from "@/data/starter/exercise-media";
import { selectBaseExercises } from "./domain/base-selection";

/**
 * Inserts any built-in exercise that does not exist yet. Idempotent.
 * Returns a map of built-in slug -> exercise id.
 */
export async function ensureBuiltInExercises(executor: DbExecutor): Promise<Map<string, string>> {
  const existing = await executor
    .select({ id: exercises.id, slug: exercises.slug })
    .from(exercises)
    .where(isNull(exercises.ownerId));

  const idBySlug = new Map(existing.map((row) => [row.slug, row.id]));
  const missing = EXERCISE_CATALOG.filter((entry) => !idBySlug.has(entry.slug));

  if (missing.length > 0) {
    const inserted = await executor
      .insert(exercises)
      .values(
        missing.map((entry) => ({
          ownerId: null,
          slug: entry.slug,
          name: entry.name,
          primaryMuscle: entry.primaryMuscle,
          movementType: entry.movementType,
          equipment: entry.equipment,
          defaultSets: entry.defaultSets,
          defaultRepMin: entry.defaultRepMin,
          defaultRepMax: entry.defaultRepMax,
        })),
      )
      .returning({ id: exercises.id, slug: exercises.slug });

    for (const row of inserted) idBySlug.set(row.slug, row.id);

    const muscleRows = missing.flatMap((entry) => {
      const exerciseId = idBySlug.get(entry.slug);
      if (!exerciseId) return [];
      return entry.secondaryMuscles.map((muscle) => ({ exerciseId, muscle }));
    });
    if (muscleRows.length > 0) {
      await executor.insert(exerciseMuscles).values(muscleRows).onConflictDoNothing();
    }
  }

  await syncBuiltInMedia(executor);
  return idBySlug;
}

/** Built-in exercises always carry the latest demo photos and instructions from the media file. */
async function syncBuiltInMedia(executor: DbExecutor): Promise<void> {
  for (const [slug, media] of Object.entries(EXERCISE_MEDIA)) {
    if (media.images.length === 0) continue;
    await executor
      .update(exercises)
      .set({
        imageUrl: media.images[0] ?? null,
        imageUrls: media.images,
        instructions: media.instructions.length > 0 ? media.instructions.join("\n") : null,
      })
      .where(and(isNull(exercises.ownerId), eq(exercises.slug, slug)));
  }
}

/** Loads the wider exercise library (generated by `pnpm media:library`). Idempotent; a no-op while the file is empty. */
export async function ensureLibraryExercises(executor: DbExecutor): Promise<number> {
  if (EXERCISE_LIBRARY.length === 0) return 0;

  const existing = await executor.select({ slug: exercises.slug }).from(exercises).where(isNull(exercises.ownerId));
  const known = new Set(existing.map((row) => row.slug));
  const missing = EXERCISE_LIBRARY.filter((entry) => !known.has(entry.slug));

  const CHUNK = 150;
  for (let start = 0; start < missing.length; start += CHUNK) {
    const chunk = missing.slice(start, start + CHUNK);
    const inserted = await executor
      .insert(exercises)
      .values(
        chunk.map((entry) => ({
          ownerId: null,
          slug: entry.slug,
          name: entry.name,
          primaryMuscle: entry.primaryMuscle,
          movementType: entry.movementType,
          equipment: entry.equipment,
          imageUrl: entry.images[0] ?? null,
          imageUrls: entry.images,
          instructions: entry.instructions.length > 0 ? entry.instructions.join("\n") : null,
        })),
      )
      .returning({ id: exercises.id, slug: exercises.slug });

    const idBySlug = new Map(inserted.map((row) => [row.slug, row.id]));
    const muscles = chunk.flatMap((entry) => {
      const exerciseId = idBySlug.get(entry.slug);
      return exerciseId ? entry.secondaryMuscles.map((muscle) => ({ exerciseId, muscle })) : [];
    });
    if (muscles.length > 0) await executor.insert(exerciseMuscles).values(muscles).onConflictDoNothing();
  }
  return missing.length;
}

/**
 * Makes sure every muscle group has at least 20 built-in exercises to pick from when editing a routine: adds, from
 * the curated reserve, only what the library and the starter catalog do not already cover. Idempotent.
 */
export async function ensureBaseExercises(executor: DbExecutor): Promise<number> {
  const existing = await executor
    .select({ slug: exercises.slug, name: exercises.name, primaryMuscle: exercises.primaryMuscle, archivedAt: exercises.archivedAt })
    .from(exercises)
    .where(isNull(exercises.ownerId));

  const missing = selectBaseExercises(
    BASE_EXERCISES,
    existing.map((row) => ({ slug: row.slug, name: row.name, primaryMuscle: row.primaryMuscle, archived: row.archivedAt !== null })),
  );
  if (missing.length === 0) return 0;

  const inserted = await executor
    .insert(exercises)
    .values(
      missing.map((entry) => ({
        ownerId: null,
        slug: entry.slug,
        name: entry.name,
        primaryMuscle: entry.primaryMuscle,
        movementType: entry.movementType,
        equipment: entry.equipment,
        defaultSets: entry.defaultSets,
        defaultRepMin: entry.defaultRepMin,
        defaultRepMax: entry.defaultRepMax,
      })),
    )
    .returning({ id: exercises.id, slug: exercises.slug });

  const idBySlug = new Map(inserted.map((row) => [row.slug, row.id]));
  const muscles = missing.flatMap((entry) => {
    const exerciseId = idBySlug.get(entry.slug);
    return exerciseId ? entry.secondaryMuscles.map((muscle) => ({ exerciseId, muscle })) : [];
  });
  if (muscles.length > 0) await executor.insert(exerciseMuscles).values(muscles).onConflictDoNothing();
  return missing.length;
}
