import library from "./exercise-library.json";
import type { Equipment, MovementType, MuscleGroup } from "@/lib/db/schema/enums";

export interface LibraryExercise {
  /** "lib-<free-exercise-db id>" */
  slug: string;
  name: string;
  primaryMuscle: MuscleGroup;
  secondaryMuscles: MuscleGroup[];
  movementType: MovementType;
  equipment: Equipment | null;
  images: string[];
  instructions: string[];
}

/**
 * The wider exercise library (strength, powerlifting, olympic lifts, strongman) from free-exercise-db.
 * Generated by `pnpm media:library`; empty until you run it.
 */
export const EXERCISE_LIBRARY = library as unknown as readonly LibraryExercise[];
