#!/bin/sh
# Fails if a data file that only exists in git (not in the zips) is missing on disk or empty:
# the exercise library generated by `pnpm media:library`.
#   pnpm check:data        (also runs before every `git push`, see .githooks/pre-push)
set -eu

LIBRARY="src/data/starter/exercise-library.json"

if [ ! -f "$LIBRARY" ]; then
  echo "ERROR: $LIBRARY is missing on disk."
  echo "Restore it from the last commit:  git checkout -- $LIBRARY"
  exit 1
fi

# "[]" (2 characters, plus a newline) is the empty placeholder: it would wipe the library from the repository.
if [ "$(tr -d ' \n\r' < "$LIBRARY")" = "[]" ] && git rev-parse --verify HEAD >/dev/null 2>&1 && [ "$(git cat-file -s "HEAD:$LIBRARY" 2>/dev/null || echo 0)" -gt 10 ]; then
  echo "ERROR: $LIBRARY is an empty list but the last commit has the real library."
  echo "Restore it:  git checkout -- $LIBRARY"
  exit 1
fi

echo "OK: exercise library present ($(wc -c < "$LIBRARY" | tr -d ' ') bytes)."
